cmake_minimum_required(VERSION 2.8.11)
project(calseek)

# CMake include guard
if(commands_config_included)
  return()
endif(commands_config_included)
set(commands_config_included true)

include(${CMAKE_CURRENT_SOURCE_DIR}/../config.cmake)

include(${DIR_MZN}/cmd_field/cmd_field.cmake)

message("\n###### config(commands) #######")

set(DIR_COMMANDS ${DIR_MZN}/commands)

include_directories(${DIR_COMMANDS}/inc/)

set(SOURCES_AG_COMMANDS  ${DIR_COMMANDS}/src_autogenerated/qdp_crc.cpp)